pipeline {
    agent any
        stages {
            stage ('Build') {
                steps {
                    sh   'echo Running build phase. '
                    sh   'python file1.py'
                }
            }
           stage('Test'){
               steps{
                sh  "echo build tests"
                sh  'python test_file1.py'
                     }
                }
           stage("Report"){
                 steps {
                    echo "Code Coverage"
                    sh  '''
                            coverage run test_file1.py
                            coverage report
                            coverage xml -o coverage.xml
                        '''
                        }
                 post{
                always{
                    step([$class: 'CoberturaPublisher',
                                   autoUpdateHealth: false,
                                   autoUpdateStability: false,
                                   coberturaReportFile: 'reports/coverage.xml',
                                   failNoReports: false,
                                   failUnhealthy: false,
                                   failUnstable: false,
                                   maxNumberOfBuilds: 10,
                                   onlyStable: false,
                                   sourceEncoding: 'ASCII',
                                   zoomCoverageChart: false])
                }
            }
        }
    }
}
